version: '3.4'

services:
  chatroom.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
        - chatroom.sql
  chatroom.sql:
    environment:
      - SA_PASSWORD=1Secure*Password1
      - ACCEPT_EULA=Y
    ports:
      - "1433"
  chatroom.mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1Mongo*Password1
    ports:
      - "27017"